// Code generated by protoc-gen-go.
// source: 3.proto
// DO NOT EDIT!

/*
Package toutiao_ssp_api is a generated protocol buffer package.

It is generated from these files:
	3.proto

It has these top-level messages:
	Pmp
	AdSlot
	Publisher
	Content
	App
	Geo
	Device
	Data
	User
	PrivateReq
	BidRequest
	MaterialMeta
	Bid
	SeatBid
	BidResponse
	DspClickNotification
*/
package today

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdType int32

const (
	AdType_TOUTIAO_FEED_LP_LARGE        AdType = 1
	AdType_TOUTIAO_FEED_LP_SMALL        AdType = 2
	AdType_TOUTIAO_FEED_APP_LARGE       AdType = 4
	AdType_TOUTIAO_FEED_APP_SMALL       AdType = 3
	AdType_TOUTIAO_DETAIL_LP_GRAPHIC    AdType = 5
	AdType_TOUTIAO_DETAIL_LP_BANNER     AdType = 6
	AdType_TUANZI_FEED_APP              AdType = 7
	AdType_TOUTIAO_DETAIL_APP_BANNER    AdType = 9
	AdType_TOUTIAO_DETAIL_LP_TEXT_IMAGE AdType = 10
	AdType_TOUTIAO_FEED_LP_GROUP        AdType = 11
	AdType_TOUTIAO_VIDEO_PATCH          AdType = 12
	AdType_NETWORK_SPLASH               AdType = 13
	AdType_TOUTIAO_SPLASH               AdType = 14
	AdType_DUANZI_FEED_LP_LARGE         AdType = 15
	AdType_DUANZI_FEED_LP_SMALL         AdType = 16
	AdType_DUANZI_FEED_LP_GROUP         AdType = 17
	AdType_TOUTIAO_FEED_APP_GROUP       AdType = 18
	AdType_TOUTIAO_RECOMMEND_LP_SMALL   AdType = 19
	AdType_TOUTIAO_FEED_LP_VIDEO        AdType = 20
	AdType_TOUTIAO_FEED_APP_VIDEO       AdType = 21
	AdType_TOUTIAO_RECOMMEND_APP_SMALL  AdType = 22
	AdType_TOUTIAO_GALLERY_LP           AdType = 23
)

var AdType_name = map[int32]string{
	1:  "TOUTIAO_FEED_LP_LARGE",
	2:  "TOUTIAO_FEED_LP_SMALL",
	4:  "TOUTIAO_FEED_APP_LARGE",
	3:  "TOUTIAO_FEED_APP_SMALL",
	5:  "TOUTIAO_DETAIL_LP_GRAPHIC",
	6:  "TOUTIAO_DETAIL_LP_BANNER",
	7:  "TUANZI_FEED_APP",
	9:  "TOUTIAO_DETAIL_APP_BANNER",
	10: "TOUTIAO_DETAIL_LP_TEXT_IMAGE",
	11: "TOUTIAO_FEED_LP_GROUP",
	12: "TOUTIAO_VIDEO_PATCH",
	13: "NETWORK_SPLASH",
	14: "TOUTIAO_SPLASH",
	15: "DUANZI_FEED_LP_LARGE",
	16: "DUANZI_FEED_LP_SMALL",
	17: "DUANZI_FEED_LP_GROUP",
	18: "TOUTIAO_FEED_APP_GROUP",
	19: "TOUTIAO_RECOMMEND_LP_SMALL",
	20: "TOUTIAO_FEED_LP_VIDEO",
	21: "TOUTIAO_FEED_APP_VIDEO",
	22: "TOUTIAO_RECOMMEND_APP_SMALL",
	23: "TOUTIAO_GALLERY_LP",
}
var AdType_value = map[string]int32{
	"TOUTIAO_FEED_LP_LARGE":        1,
	"TOUTIAO_FEED_LP_SMALL":        2,
	"TOUTIAO_FEED_APP_LARGE":       4,
	"TOUTIAO_FEED_APP_SMALL":       3,
	"TOUTIAO_DETAIL_LP_GRAPHIC":    5,
	"TOUTIAO_DETAIL_LP_BANNER":     6,
	"TUANZI_FEED_APP":              7,
	"TOUTIAO_DETAIL_APP_BANNER":    9,
	"TOUTIAO_DETAIL_LP_TEXT_IMAGE": 10,
	"TOUTIAO_FEED_LP_GROUP":        11,
	"TOUTIAO_VIDEO_PATCH":          12,
	"NETWORK_SPLASH":               13,
	"TOUTIAO_SPLASH":               14,
	"DUANZI_FEED_LP_LARGE":         15,
	"DUANZI_FEED_LP_SMALL":         16,
	"DUANZI_FEED_LP_GROUP":         17,
	"TOUTIAO_FEED_APP_GROUP":       18,
	"TOUTIAO_RECOMMEND_LP_SMALL":   19,
	"TOUTIAO_FEED_LP_VIDEO":        20,
	"TOUTIAO_FEED_APP_VIDEO":       21,
	"TOUTIAO_RECOMMEND_APP_SMALL":  22,
	"TOUTIAO_GALLERY_LP":           23,
}

func (x AdType) Enum() *AdType {
	p := new(AdType)
	*p = x
	return p
}
func (x AdType) String() string {
	return proto.EnumName(AdType_name, int32(x))
}
func (x *AdType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AdType_value, data, "AdType")
	if err != nil {
		return err
	}
	*x = AdType(value)
	return nil
}
func (AdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AdSlot_Position int32

const (
	AdSlot_SPLASH    AdSlot_Position = 1
	AdSlot_FEED      AdSlot_Position = 2
	AdSlot_DETAIL    AdSlot_Position = 4
	AdSlot_RECOMMEND AdSlot_Position = 8
	AdSlot_GALLERY   AdSlot_Position = 16
)

var AdSlot_Position_name = map[int32]string{
	1:  "SPLASH",
	2:  "FEED",
	4:  "DETAIL",
	8:  "RECOMMEND",
	16: "GALLERY",
}
var AdSlot_Position_value = map[string]int32{
	"SPLASH":    1,
	"FEED":      2,
	"DETAIL":    4,
	"RECOMMEND": 8,
	"GALLERY":   16,
}

func (x AdSlot_Position) Enum() *AdSlot_Position {
	p := new(AdSlot_Position)
	*p = x
	return p
}
func (x AdSlot_Position) String() string {
	return proto.EnumName(AdSlot_Position_name, int32(x))
}
func (x *AdSlot_Position) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AdSlot_Position_value, data, "AdSlot_Position")
	if err != nil {
		return err
	}
	*x = AdSlot_Position(value)
	return nil
}
func (AdSlot_Position) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Device_ConnectionType int32

const (
	Device_Honeycomb Device_ConnectionType = 1
	Device_WIFI      Device_ConnectionType = 2
	Device_UNKNOWN   Device_ConnectionType = 3
	Device_NT_2G     Device_ConnectionType = 4
	Device_NT_4G     Device_ConnectionType = 5
)

var Device_ConnectionType_name = map[int32]string{
	1: "Honeycomb",
	2: "WIFI",
	3: "UNKNOWN",
	4: "NT_2G",
	5: "NT_4G",
}
var Device_ConnectionType_value = map[string]int32{
	"Honeycomb": 1,
	"WIFI":      2,
	"UNKNOWN":   3,
	"NT_2G":     4,
	"NT_4G":     5,
}

func (x Device_ConnectionType) Enum() *Device_ConnectionType {
	p := new(Device_ConnectionType)
	*p = x
	return p
}
func (x Device_ConnectionType) String() string {
	return proto.EnumName(Device_ConnectionType_name, int32(x))
}
func (x *Device_ConnectionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_ConnectionType_value, data, "Device_ConnectionType")
	if err != nil {
		return err
	}
	*x = Device_ConnectionType(value)
	return nil
}
func (Device_ConnectionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type Device_DeviceType int32

const (
	Device_PHONE  Device_DeviceType = 1
	Device_TABLET Device_DeviceType = 2
)

var Device_DeviceType_name = map[int32]string{
	1: "PHONE",
	2: "TABLET",
}
var Device_DeviceType_value = map[string]int32{
	"PHONE":  1,
	"TABLET": 2,
}

func (x Device_DeviceType) Enum() *Device_DeviceType {
	p := new(Device_DeviceType)
	*p = x
	return p
}
func (x Device_DeviceType) String() string {
	return proto.EnumName(Device_DeviceType_name, int32(x))
}
func (x *Device_DeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_DeviceType_value, data, "Device_DeviceType")
	if err != nil {
		return err
	}
	*x = Device_DeviceType(value)
	return nil
}
func (Device_DeviceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 1} }

type User_Gender int32

const (
	User_MALE    User_Gender = 1
	User_FEMALE  User_Gender = 2
	User_UNKNOWN User_Gender = 3
)

var User_Gender_name = map[int32]string{
	1: "MALE",
	2: "FEMALE",
	3: "UNKNOWN",
}
var User_Gender_value = map[string]int32{
	"MALE":    1,
	"FEMALE":  2,
	"UNKNOWN": 3,
}

func (x User_Gender) Enum() *User_Gender {
	p := new(User_Gender)
	*p = x
	return p
}
func (x User_Gender) String() string {
	return proto.EnumName(User_Gender_name, int32(x))
}
func (x *User_Gender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(User_Gender_value, data, "User_Gender")
	if err != nil {
		return err
	}
	*x = User_Gender(value)
	return nil
}
func (User_Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type BidRequest_BidReqType int32

const (
	BidRequest_ONLY_RETARGET    BidRequest_BidReqType = 1
	BidRequest_ONLY_DSP         BidRequest_BidReqType = 2
	BidRequest_RETARGET_AND_DSP BidRequest_BidReqType = 3
)

var BidRequest_BidReqType_name = map[int32]string{
	1: "ONLY_RETARGET",
	2: "ONLY_DSP",
	3: "RETARGET_AND_DSP",
}
var BidRequest_BidReqType_value = map[string]int32{
	"ONLY_RETARGET":    1,
	"ONLY_DSP":         2,
	"RETARGET_AND_DSP": 3,
}

func (x BidRequest_BidReqType) Enum() *BidRequest_BidReqType {
	p := new(BidRequest_BidReqType)
	*p = x
	return p
}
func (x BidRequest_BidReqType) String() string {
	return proto.EnumName(BidRequest_BidReqType_name, int32(x))
}
func (x *BidRequest_BidReqType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BidRequest_BidReqType_value, data, "BidRequest_BidReqType")
	if err != nil {
		return err
	}
	*x = BidRequest_BidReqType(value)
	return nil
}
func (BidRequest_BidReqType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

type MaterialMeta_ExternalMeta_AdvCreativeType int32

const (
	MaterialMeta_ExternalMeta_NONE   MaterialMeta_ExternalMeta_AdvCreativeType = 0
	MaterialMeta_ExternalMeta_ACTION MaterialMeta_ExternalMeta_AdvCreativeType = 2
)

var MaterialMeta_ExternalMeta_AdvCreativeType_name = map[int32]string{
	0: "NONE",
	2: "ACTION",
}
var MaterialMeta_ExternalMeta_AdvCreativeType_value = map[string]int32{
	"NONE":   0,
	"ACTION": 2,
}

func (x MaterialMeta_ExternalMeta_AdvCreativeType) Enum() *MaterialMeta_ExternalMeta_AdvCreativeType {
	p := new(MaterialMeta_ExternalMeta_AdvCreativeType)
	*p = x
	return p
}
func (x MaterialMeta_ExternalMeta_AdvCreativeType) String() string {
	return proto.EnumName(MaterialMeta_ExternalMeta_AdvCreativeType_name, int32(x))
}
func (x *MaterialMeta_ExternalMeta_AdvCreativeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MaterialMeta_ExternalMeta_AdvCreativeType_value, data, "MaterialMeta_ExternalMeta_AdvCreativeType")
	if err != nil {
		return err
	}
	*x = MaterialMeta_ExternalMeta_AdvCreativeType(value)
	return nil
}
func (MaterialMeta_ExternalMeta_AdvCreativeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 1, 0}
}

type MaterialMeta_ExternalMeta_ButtonText int32

const (
	MaterialMeta_ExternalMeta_PHONE_DIAL      MaterialMeta_ExternalMeta_ButtonText = 0
	MaterialMeta_ExternalMeta_CONSULT_HOTLINE MaterialMeta_ExternalMeta_ButtonText = 1
	MaterialMeta_ExternalMeta_PHONE_CONSULT   MaterialMeta_ExternalMeta_ButtonText = 2
	MaterialMeta_ExternalMeta_ATONCE_DIAL     MaterialMeta_ExternalMeta_ButtonText = 3
	MaterialMeta_ExternalMeta_CONSULT_PHONE   MaterialMeta_ExternalMeta_ButtonText = 4
	MaterialMeta_ExternalMeta_FREE_HOTLINE    MaterialMeta_ExternalMeta_ButtonText = 5
	MaterialMeta_ExternalMeta_JOIN_HOTLINE    MaterialMeta_ExternalMeta_ButtonText = 6
	MaterialMeta_ExternalMeta_ORDER_HOTLINE   MaterialMeta_ExternalMeta_ButtonText = 7
)

var MaterialMeta_ExternalMeta_ButtonText_name = map[int32]string{
	0: "PHONE_DIAL",
	1: "CONSULT_HOTLINE",
	2: "PHONE_CONSULT",
	3: "ATONCE_DIAL",
	4: "CONSULT_PHONE",
	5: "FREE_HOTLINE",
	6: "JOIN_HOTLINE",
	7: "ORDER_HOTLINE",
}
var MaterialMeta_ExternalMeta_ButtonText_value = map[string]int32{
	"PHONE_DIAL":      0,
	"CONSULT_HOTLINE": 1,
	"PHONE_CONSULT":   2,
	"ATONCE_DIAL":     3,
	"CONSULT_PHONE":   4,
	"FREE_HOTLINE":    5,
	"JOIN_HOTLINE":    6,
	"ORDER_HOTLINE":   7,
}

func (x MaterialMeta_ExternalMeta_ButtonText) Enum() *MaterialMeta_ExternalMeta_ButtonText {
	p := new(MaterialMeta_ExternalMeta_ButtonText)
	*p = x
	return p
}
func (x MaterialMeta_ExternalMeta_ButtonText) String() string {
	return proto.EnumName(MaterialMeta_ExternalMeta_ButtonText_name, int32(x))
}
func (x *MaterialMeta_ExternalMeta_ButtonText) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MaterialMeta_ExternalMeta_ButtonText_value, data, "MaterialMeta_ExternalMeta_ButtonText")
	if err != nil {
		return err
	}
	*x = MaterialMeta_ExternalMeta_ButtonText(value)
	return nil
}
func (MaterialMeta_ExternalMeta_ButtonText) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 1, 1}
}

type Bid_BidAdType int32

const (
	Bid_RETARGET_AD     Bid_BidAdType = 1
	Bid_DSP_AD          Bid_BidAdType = 2
	Bid_NON_RETARGET_AD Bid_BidAdType = 3
)

var Bid_BidAdType_name = map[int32]string{
	1: "RETARGET_AD",
	2: "DSP_AD",
	3: "NON_RETARGET_AD",
}
var Bid_BidAdType_value = map[string]int32{
	"RETARGET_AD":     1,
	"DSP_AD":          2,
	"NON_RETARGET_AD": 3,
}

func (x Bid_BidAdType) Enum() *Bid_BidAdType {
	p := new(Bid_BidAdType)
	*p = x
	return p
}
func (x Bid_BidAdType) String() string {
	return proto.EnumName(Bid_BidAdType_name, int32(x))
}
func (x *Bid_BidAdType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Bid_BidAdType_value, data, "Bid_BidAdType")
	if err != nil {
		return err
	}
	*x = Bid_BidAdType(value)
	return nil
}
func (Bid_BidAdType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{12, 0} }

type Pmp struct {
	PrivateAuction   *uint32     `protobuf:"varint,1,opt,name=private_auction,json=privateAuction" json:"private_auction,omitempty"`
	Deals            []*Pmp_Deal `protobuf:"bytes,2,rep,name=deals" json:"deals,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Pmp) Reset()                    { *m = Pmp{} }
func (m *Pmp) String() string            { return proto.CompactTextString(m) }
func (*Pmp) ProtoMessage()               {}
func (*Pmp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pmp) GetPrivateAuction() uint32 {
	if m != nil && m.PrivateAuction != nil {
		return *m.PrivateAuction
	}
	return 0
}

func (m *Pmp) GetDeals() []*Pmp_Deal {
	if m != nil {
		return m.Deals
	}
	return nil
}

type Pmp_Deal struct {
	Id               *uint32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	BidFloor         *uint32  `protobuf:"varint,2,opt,name=bid_floor,json=bidFloor" json:"bid_floor,omitempty"`
	Wseat            []string `protobuf:"bytes,3,rep,name=wseat" json:"wseat,omitempty"`
	Wadomain         []string `protobuf:"bytes,4,rep,name=wadomain" json:"wadomain,omitempty"`
	At               *uint32  `protobuf:"varint,5,opt,name=at" json:"at,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Pmp_Deal) Reset()                    { *m = Pmp_Deal{} }
func (m *Pmp_Deal) String() string            { return proto.CompactTextString(m) }
func (*Pmp_Deal) ProtoMessage()               {}
func (*Pmp_Deal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Pmp_Deal) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Pmp_Deal) GetBidFloor() uint32 {
	if m != nil && m.BidFloor != nil {
		return *m.BidFloor
	}
	return 0
}

func (m *Pmp_Deal) GetWseat() []string {
	if m != nil {
		return m.Wseat
	}
	return nil
}

func (m *Pmp_Deal) GetWadomain() []string {
	if m != nil {
		return m.Wadomain
	}
	return nil
}

func (m *Pmp_Deal) GetAt() uint32 {
	if m != nil && m.At != nil {
		return *m.At
	}
	return 0
}

type AdSlot struct {
	Id               *string          `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Banner           []*AdSlot_Banner `protobuf:"bytes,2,rep,name=banner" json:"banner,omitempty"`
	AdType           []AdType         `protobuf:"varint,3,rep,name=ad_type,json=adType,enum=toutiao_ssp.api.AdType" json:"ad_type,omitempty"`
	BidFloor         *uint32          `protobuf:"varint,4,opt,name=bid_floor,json=bidFloor" json:"bid_floor,omitempty"`
	Pmp              *Pmp             `protobuf:"bytes,5,opt,name=pmp" json:"pmp,omitempty"`
	PatchVideoLength *uint32          `protobuf:"varint,6,opt,name=patch_video_length,json=patchVideoLength" json:"patch_video_length,omitempty"`
	PatchVideoTitle  *string          `protobuf:"bytes,7,opt,name=patch_video_title,json=patchVideoTitle" json:"patch_video_title,omitempty"`
	ChannelId        *uint64          `protobuf:"varint,8,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	Timestamp        *uint64          `protobuf:"varint,9,opt,name=timestamp" json:"timestamp,omitempty"`
	Keywords         []string         `protobuf:"bytes,10,rep,name=keywords" json:"keywords,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *AdSlot) Reset()                    { *m = AdSlot{} }
func (m *AdSlot) String() string            { return proto.CompactTextString(m) }
func (*AdSlot) ProtoMessage()               {}
func (*AdSlot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AdSlot) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *AdSlot) GetBanner() []*AdSlot_Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

func (m *AdSlot) GetAdType() []AdType {
	if m != nil {
		return m.AdType
	}
	return nil
}

func (m *AdSlot) GetBidFloor() uint32 {
	if m != nil && m.BidFloor != nil {
		return *m.BidFloor
	}
	return 0
}

func (m *AdSlot) GetPmp() *Pmp {
	if m != nil {
		return m.Pmp
	}
	return nil
}

func (m *AdSlot) GetPatchVideoLength() uint32 {
	if m != nil && m.PatchVideoLength != nil {
		return *m.PatchVideoLength
	}
	return 0
}

func (m *AdSlot) GetPatchVideoTitle() string {
	if m != nil && m.PatchVideoTitle != nil {
		return *m.PatchVideoTitle
	}
	return ""
}

func (m *AdSlot) GetChannelId() uint64 {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return 0
}

func (m *AdSlot) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *AdSlot) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

type AdSlot_Banner struct {
	Width            *uint32          `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height           *uint32          `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	Pos              *AdSlot_Position `protobuf:"varint,3,req,name=pos,enum=toutiao_ssp.api.AdSlot_Position" json:"pos,omitempty"`
	Sequence         *string          `protobuf:"bytes,4,opt,name=sequence" json:"sequence,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *AdSlot_Banner) Reset()                    { *m = AdSlot_Banner{} }
func (m *AdSlot_Banner) String() string            { return proto.CompactTextString(m) }
func (*AdSlot_Banner) ProtoMessage()               {}
func (*AdSlot_Banner) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *AdSlot_Banner) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *AdSlot_Banner) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *AdSlot_Banner) GetPos() AdSlot_Position {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return AdSlot_SPLASH
}

func (m *AdSlot_Banner) GetSequence() string {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return ""
}

type Publisher struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Cat              *string `protobuf:"bytes,3,opt,name=cat" json:"cat,omitempty"`
	Domain           *string `protobuf:"bytes,4,opt,name=domain" json:"domain,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Publisher) Reset()                    { *m = Publisher{} }
func (m *Publisher) String() string            { return proto.CompactTextString(m) }
func (*Publisher) ProtoMessage()               {}
func (*Publisher) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Publisher) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Publisher) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Publisher) GetCat() string {
	if m != nil && m.Cat != nil {
		return *m.Cat
	}
	return ""
}

func (m *Publisher) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

type Content struct {
	Id               *string           `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Title            *string           `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Series           *string           `protobuf:"bytes,3,opt,name=series" json:"series,omitempty"`
	Url              *string           `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Keywords         *string           `protobuf:"bytes,5,opt,name=keywords" json:"keywords,omitempty"`
	Contentrating    *string           `protobuf:"bytes,6,opt,name=contentrating" json:"contentrating,omitempty"`
	Userrating       *string           `protobuf:"bytes,7,opt,name=userrating" json:"userrating,omitempty"`
	Context          *string           `protobuf:"bytes,8,opt,name=context" json:"context,omitempty"`
	Producer         *Content_Producer `protobuf:"bytes,9,opt,name=producer" json:"producer,omitempty"`
	Language         *string           `protobuf:"bytes,10,opt,name=language" json:"language,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Content) Reset()                    { *m = Content{} }
func (m *Content) String() string            { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()               {}
func (*Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Content) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Content) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Content) GetSeries() string {
	if m != nil && m.Series != nil {
		return *m.Series
	}
	return ""
}

func (m *Content) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *Content) GetKeywords() string {
	if m != nil && m.Keywords != nil {
		return *m.Keywords
	}
	return ""
}

func (m *Content) GetContentrating() string {
	if m != nil && m.Contentrating != nil {
		return *m.Contentrating
	}
	return ""
}

func (m *Content) GetUserrating() string {
	if m != nil && m.Userrating != nil {
		return *m.Userrating
	}
	return ""
}

func (m *Content) GetContext() string {
	if m != nil && m.Context != nil {
		return *m.Context
	}
	return ""
}

func (m *Content) GetProducer() *Content_Producer {
	if m != nil {
		return m.Producer
	}
	return nil
}

func (m *Content) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

type Content_Producer struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Cat              *string `protobuf:"bytes,3,opt,name=cat" json:"cat,omitempty"`
	Domain           *string `protobuf:"bytes,4,opt,name=domain" json:"domain,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Content_Producer) Reset()                    { *m = Content_Producer{} }
func (m *Content_Producer) String() string            { return proto.CompactTextString(m) }
func (*Content_Producer) ProtoMessage()               {}
func (*Content_Producer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *Content_Producer) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Content_Producer) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Content_Producer) GetCat() string {
	if m != nil && m.Cat != nil {
		return *m.Cat
	}
	return ""
}

func (m *Content_Producer) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

type App struct {
	Id               *string    `protobuf:"bytes,1,req,name=id,def=11" json:"id,omitempty"`
	Name             *string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Domain           *string    `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	Ver              *string    `protobuf:"bytes,4,opt,name=ver" json:"ver,omitempty"`
	Bundle           *string    `protobuf:"bytes,5,opt,name=bundle" json:"bundle,omitempty"`
	Privacypolicy    *uint32    `protobuf:"varint,6,opt,name=privacypolicy" json:"privacypolicy,omitempty"`
	Paid             *uint32    `protobuf:"varint,7,opt,name=paid" json:"paid,omitempty"`
	Publisher        *Publisher `protobuf:"bytes,8,opt,name=publisher" json:"publisher,omitempty"`
	Content          *Content   `protobuf:"bytes,9,opt,name=content" json:"content,omitempty"`
	Keywords         *string    `protobuf:"bytes,10,opt,name=keywords" json:"keywords,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *App) Reset()                    { *m = App{} }
func (m *App) String() string            { return proto.CompactTextString(m) }
func (*App) ProtoMessage()               {}
func (*App) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

const Default_App_Id string = "11"

func (m *App) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return Default_App_Id
}

func (m *App) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *App) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *App) GetVer() string {
	if m != nil && m.Ver != nil {
		return *m.Ver
	}
	return ""
}

func (m *App) GetBundle() string {
	if m != nil && m.Bundle != nil {
		return *m.Bundle
	}
	return ""
}

func (m *App) GetPrivacypolicy() uint32 {
	if m != nil && m.Privacypolicy != nil {
		return *m.Privacypolicy
	}
	return 0
}

func (m *App) GetPaid() uint32 {
	if m != nil && m.Paid != nil {
		return *m.Paid
	}
	return 0
}

func (m *App) GetPublisher() *Publisher {
	if m != nil {
		return m.Publisher
	}
	return nil
}

func (m *App) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *App) GetKeywords() string {
	if m != nil && m.Keywords != nil {
		return *m.Keywords
	}
	return ""
}

type Geo struct {
	Lat              *float64 `protobuf:"fixed64,1,opt,name=lat" json:"lat,omitempty"`
	Lon              *float64 `protobuf:"fixed64,2,opt,name=lon" json:"lon,omitempty"`
	Country          *string  `protobuf:"bytes,3,opt,name=country" json:"country,omitempty"`
	Region           *string  `protobuf:"bytes,4,opt,name=region" json:"region,omitempty"`
	City             *string  `protobuf:"bytes,5,opt,name=city" json:"city,omitempty"`
	Type             *string  `protobuf:"bytes,6,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Geo) Reset()                    { *m = Geo{} }
func (m *Geo) String() string            { return proto.CompactTextString(m) }
func (*Geo) ProtoMessage()               {}
func (*Geo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Geo) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Geo) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func (m *Geo) GetCountry() string {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return ""
}

func (m *Geo) GetRegion() string {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return ""
}

func (m *Geo) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *Geo) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

type Device struct {
	Dnt              *bool                  `protobuf:"varint,1,req,name=dnt" json:"dnt,omitempty"`
	Ua               *string                `protobuf:"bytes,2,req,name=ua" json:"ua,omitempty"`
	Ip               *string                `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
	Geo              *Geo                   `protobuf:"bytes,4,opt,name=geo" json:"geo,omitempty"`
	DeviceId         *string                `protobuf:"bytes,5,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	DeviceIdMd5      *string                `protobuf:"bytes,6,opt,name=device_id_md5,json=deviceIdMd5" json:"device_id_md5,omitempty"`
	Carrier          *string                `protobuf:"bytes,7,opt,name=carrier" json:"carrier,omitempty"`
	Language         *string                `protobuf:"bytes,8,opt,name=language" json:"language,omitempty"`
	Make             *string                `protobuf:"bytes,9,opt,name=make" json:"make,omitempty"`
	Model            *string                `protobuf:"bytes,10,opt,name=model" json:"model,omitempty"`
	Os               *string                `protobuf:"bytes,11,opt,name=os" json:"os,omitempty"`
	Osv              *string                `protobuf:"bytes,12,opt,name=osv" json:"osv,omitempty"`
	Js               *bool                  `protobuf:"varint,13,opt,name=js" json:"js,omitempty"`
	ConnectionType   *Device_ConnectionType `protobuf:"varint,14,opt,name=connection_type,json=connectionType,enum=toutiao_ssp.api.Device_ConnectionType" json:"connection_type,omitempty"`
	DeviceType       *Device_DeviceType     `protobuf:"varint,15,opt,name=device_type,json=deviceType,enum=toutiao_ssp.api.Device_DeviceType" json:"device_type,omitempty"`
	AndroidId        *string                `protobuf:"bytes,16,opt,name=android_id,json=androidId" json:"android_id,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Device) GetDnt() bool {
	if m != nil && m.Dnt != nil {
		return *m.Dnt
	}
	return false
}

func (m *Device) GetUa() string {
	if m != nil && m.Ua != nil {
		return *m.Ua
	}
	return ""
}

func (m *Device) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *Device) GetGeo() *Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *Device) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *Device) GetDeviceIdMd5() string {
	if m != nil && m.DeviceIdMd5 != nil {
		return *m.DeviceIdMd5
	}
	return ""
}

func (m *Device) GetCarrier() string {
	if m != nil && m.Carrier != nil {
		return *m.Carrier
	}
	return ""
}

func (m *Device) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *Device) GetMake() string {
	if m != nil && m.Make != nil {
		return *m.Make
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

func (m *Device) GetOs() string {
	if m != nil && m.Os != nil {
		return *m.Os
	}
	return ""
}

func (m *Device) GetOsv() string {
	if m != nil && m.Osv != nil {
		return *m.Osv
	}
	return ""
}

func (m *Device) GetJs() bool {
	if m != nil && m.Js != nil {
		return *m.Js
	}
	return false
}

func (m *Device) GetConnectionType() Device_ConnectionType {
	if m != nil && m.ConnectionType != nil {
		return *m.ConnectionType
	}
	return Device_Honeycomb
}

func (m *Device) GetDeviceType() Device_DeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return Device_PHONE
}

func (m *Device) GetAndroidId() string {
	if m != nil && m.AndroidId != nil {
		return *m.AndroidId
	}
	return ""
}

type Data struct {
	Id               *string         `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name             *string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Segment          []*Data_Segment `protobuf:"bytes,3,rep,name=segment" json:"segment,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Data) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Data) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Data) GetSegment() []*Data_Segment {
	if m != nil {
		return m.Segment
	}
	return nil
}

type Data_Segment struct {
	Id               *string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Data_Segment) Reset()                    { *m = Data_Segment{} }
func (m *Data_Segment) String() string            { return proto.CompactTextString(m) }
func (*Data_Segment) ProtoMessage()               {}
func (*Data_Segment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *Data_Segment) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Data_Segment) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Data_Segment) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type User struct {
	Id               *string      `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	BuyerId          *string      `protobuf:"bytes,2,opt,name=buyer_id,json=buyerId" json:"buyer_id,omitempty"`
	Yob              *string      `protobuf:"bytes,3,opt,name=yob" json:"yob,omitempty"`
	Gender           *User_Gender `protobuf:"varint,4,opt,name=gender,enum=toutiao_ssp.api.User_Gender" json:"gender,omitempty"`
	Keywords         *string      `protobuf:"bytes,5,opt,name=keywords" json:"keywords,omitempty"`
	Geo              *Geo         `protobuf:"bytes,6,opt,name=geo" json:"geo,omitempty"`
	Data             []*Data      `protobuf:"bytes,7,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *User) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *User) GetBuyerId() string {
	if m != nil && m.BuyerId != nil {
		return *m.BuyerId
	}
	return ""
}

func (m *User) GetYob() string {
	if m != nil && m.Yob != nil {
		return *m.Yob
	}
	return ""
}

func (m *User) GetGender() User_Gender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return User_MALE
}

func (m *User) GetKeywords() string {
	if m != nil && m.Keywords != nil {
		return *m.Keywords
	}
	return ""
}

func (m *User) GetGeo() *Geo {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *User) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type PrivateReq struct {
	Materials []*PrivateReq_MaterialInfo `protobuf:"bytes,1,rep,name=materials" json:"materials,omitempty"`
	// 京东地域汉字
	AreaCnName *string `protobuf:"bytes,2,opt,name=area_cn_name,json=areaCnName" json:"area_cn_name,omitempty"`
	// 京东地域id
	AreaId           *string `protobuf:"bytes,3,opt,name=area_id,json=areaId" json:"area_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrivateReq) Reset()                    { *m = PrivateReq{} }
func (m *PrivateReq) String() string            { return proto.CompactTextString(m) }
func (*PrivateReq) ProtoMessage()               {}
func (*PrivateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PrivateReq) GetMaterials() []*PrivateReq_MaterialInfo {
	if m != nil {
		return m.Materials
	}
	return nil
}

func (m *PrivateReq) GetAreaCnName() string {
	if m != nil && m.AreaCnName != nil {
		return *m.AreaCnName
	}
	return ""
}

func (m *PrivateReq) GetAreaId() string {
	if m != nil && m.AreaId != nil {
		return *m.AreaId
	}
	return ""
}

type PrivateReq_MaterialInfo struct {
	// 请求素材id
	AdId *string `protobuf:"bytes,1,opt,name=ad_id,json=adId" json:"ad_id,omitempty"`
	// 请求广告主id
	AdvertiserId     *string `protobuf:"bytes,2,opt,name=advertiser_id,json=advertiserId" json:"advertiser_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PrivateReq_MaterialInfo) Reset()                    { *m = PrivateReq_MaterialInfo{} }
func (m *PrivateReq_MaterialInfo) String() string            { return proto.CompactTextString(m) }
func (*PrivateReq_MaterialInfo) ProtoMessage()               {}
func (*PrivateReq_MaterialInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *PrivateReq_MaterialInfo) GetAdId() string {
	if m != nil && m.AdId != nil {
		return *m.AdId
	}
	return ""
}

func (m *PrivateReq_MaterialInfo) GetAdvertiserId() string {
	if m != nil && m.AdvertiserId != nil {
		return *m.AdvertiserId
	}
	return ""
}

type BidRequest struct {
	RequestId        *string                `protobuf:"bytes,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	ApiVersion       *string                `protobuf:"bytes,2,req,name=api_version,json=apiVersion" json:"api_version,omitempty"`
	Adslots          []*AdSlot              `protobuf:"bytes,3,rep,name=adslots" json:"adslots,omitempty"`
	App              *App                   `protobuf:"bytes,4,req,name=app" json:"app,omitempty"`
	Device           *Device                `protobuf:"bytes,5,req,name=device" json:"device,omitempty"`
	User             *User                  `protobuf:"bytes,6,req,name=user" json:"user,omitempty"`
	BidReqType       *BidRequest_BidReqType `protobuf:"varint,7,opt,name=bid_req_type,json=bidReqType,enum=toutiao_ssp.api.BidRequest_BidReqType,def=2" json:"bid_req_type,omitempty"`
	Preq             *PrivateReq            `protobuf:"bytes,8,opt,name=preq" json:"preq,omitempty"`
	DspId            *uint32                `protobuf:"varint,9,req,name=dsp_id,json=dspId" json:"dsp_id,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *BidRequest) Reset()                    { *m = BidRequest{} }
func (m *BidRequest) String() string            { return proto.CompactTextString(m) }
func (*BidRequest) ProtoMessage()               {}
func (*BidRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

const Default_BidRequest_BidReqType BidRequest_BidReqType = BidRequest_ONLY_DSP

func (m *BidRequest) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *BidRequest) GetApiVersion() string {
	if m != nil && m.ApiVersion != nil {
		return *m.ApiVersion
	}
	return ""
}

func (m *BidRequest) GetAdslots() []*AdSlot {
	if m != nil {
		return m.Adslots
	}
	return nil
}

func (m *BidRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *BidRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *BidRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BidRequest) GetBidReqType() BidRequest_BidReqType {
	if m != nil && m.BidReqType != nil {
		return *m.BidReqType
	}
	return Default_BidRequest_BidReqType
}

func (m *BidRequest) GetPreq() *PrivateReq {
	if m != nil {
		return m.Preq
	}
	return nil
}

func (m *BidRequest) GetDspId() uint32 {
	if m != nil && m.DspId != nil {
		return *m.DspId
	}
	return 0
}

type MaterialMeta struct {
	AdType             *AdType                    `protobuf:"varint,1,req,name=ad_type,json=adType,enum=toutiao_ssp.api.AdType" json:"ad_type,omitempty"`
	Nurl               *string                    `protobuf:"bytes,2,req,name=nurl" json:"nurl,omitempty"`
	Title              *string                    `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Source             *string                    `protobuf:"bytes,4,req,name=source" json:"source,omitempty"`
	ImageBanner        *MaterialMeta_ImageMeta    `protobuf:"bytes,5,opt,name=image_banner,json=imageBanner" json:"image_banner,omitempty"`
	External           *MaterialMeta_ExternalMeta `protobuf:"bytes,6,opt,name=external" json:"external,omitempty"`
	AndroidApp         *MaterialMeta_AndroidApp   `protobuf:"bytes,7,opt,name=android_app,json=androidApp" json:"android_app,omitempty"`
	IosApp             *MaterialMeta_IosApp       `protobuf:"bytes,8,opt,name=ios_app,json=iosApp" json:"ios_app,omitempty"`
	ShowUrl            []string                   `protobuf:"bytes,9,rep,name=show_url,json=showUrl" json:"show_url,omitempty"`
	ClickUrl           []string                   `protobuf:"bytes,10,rep,name=click_url,json=clickUrl" json:"click_url,omitempty"`
	IsInapp            *bool                      `protobuf:"varint,11,opt,name=is_inapp,json=isInapp" json:"is_inapp,omitempty"`
	Ext                *string                    `protobuf:"bytes,12,opt,name=ext" json:"ext,omitempty"`
	LpOpenUrl          *string                    `protobuf:"bytes,13,opt,name=lp_open_url,json=lpOpenUrl" json:"lp_open_url,omitempty"`
	VideoPlayStartUrl  []string                   `protobuf:"bytes,14,rep,name=video_play_start_url,json=videoPlayStartUrl" json:"video_play_start_url,omitempty"`
	VideoPlayFinishUrl []string                   `protobuf:"bytes,15,rep,name=video_play_finish_url,json=videoPlayFinishUrl" json:"video_play_finish_url,omitempty"`
	SourceAvatar       *string                    `protobuf:"bytes,16,opt,name=source_avatar,json=sourceAvatar" json:"source_avatar,omitempty"`
	SplashCreatives    []*MaterialMeta_ImageMeta  `protobuf:"bytes,17,rep,name=splash_creatives,json=splashCreatives" json:"splash_creatives,omitempty"`
	VideoUrl           *string                    `protobuf:"bytes,18,opt,name=video_url,json=videoUrl" json:"video_url,omitempty"`
	VideoPlayUrl       []string                   `protobuf:"bytes,19,rep,name=video_play_url,json=videoPlayUrl" json:"video_play_url,omitempty"`
	VideoPlayValidUrl  []string                   `protobuf:"bytes,20,rep,name=video_play_valid_url,json=videoPlayValidUrl" json:"video_play_valid_url,omitempty"`
	SubTitle           *string                    `protobuf:"bytes,21,opt,name=sub_title,json=subTitle" json:"sub_title,omitempty"`
	XXX_unrecognized   []byte                     `json:"-"`
}

func (m *MaterialMeta) Reset()                    { *m = MaterialMeta{} }
func (m *MaterialMeta) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta) ProtoMessage()               {}
func (*MaterialMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MaterialMeta) GetAdType() AdType {
	if m != nil && m.AdType != nil {
		return *m.AdType
	}
	return AdType_TOUTIAO_FEED_LP_LARGE
}

func (m *MaterialMeta) GetNurl() string {
	if m != nil && m.Nurl != nil {
		return *m.Nurl
	}
	return ""
}

func (m *MaterialMeta) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *MaterialMeta) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *MaterialMeta) GetImageBanner() *MaterialMeta_ImageMeta {
	if m != nil {
		return m.ImageBanner
	}
	return nil
}

func (m *MaterialMeta) GetExternal() *MaterialMeta_ExternalMeta {
	if m != nil {
		return m.External
	}
	return nil
}

func (m *MaterialMeta) GetAndroidApp() *MaterialMeta_AndroidApp {
	if m != nil {
		return m.AndroidApp
	}
	return nil
}

func (m *MaterialMeta) GetIosApp() *MaterialMeta_IosApp {
	if m != nil {
		return m.IosApp
	}
	return nil
}

func (m *MaterialMeta) GetShowUrl() []string {
	if m != nil {
		return m.ShowUrl
	}
	return nil
}

func (m *MaterialMeta) GetClickUrl() []string {
	if m != nil {
		return m.ClickUrl
	}
	return nil
}

func (m *MaterialMeta) GetIsInapp() bool {
	if m != nil && m.IsInapp != nil {
		return *m.IsInapp
	}
	return false
}

func (m *MaterialMeta) GetExt() string {
	if m != nil && m.Ext != nil {
		return *m.Ext
	}
	return ""
}

func (m *MaterialMeta) GetLpOpenUrl() string {
	if m != nil && m.LpOpenUrl != nil {
		return *m.LpOpenUrl
	}
	return ""
}

func (m *MaterialMeta) GetVideoPlayStartUrl() []string {
	if m != nil {
		return m.VideoPlayStartUrl
	}
	return nil
}

func (m *MaterialMeta) GetVideoPlayFinishUrl() []string {
	if m != nil {
		return m.VideoPlayFinishUrl
	}
	return nil
}

func (m *MaterialMeta) GetSourceAvatar() string {
	if m != nil && m.SourceAvatar != nil {
		return *m.SourceAvatar
	}
	return ""
}

func (m *MaterialMeta) GetSplashCreatives() []*MaterialMeta_ImageMeta {
	if m != nil {
		return m.SplashCreatives
	}
	return nil
}

func (m *MaterialMeta) GetVideoUrl() string {
	if m != nil && m.VideoUrl != nil {
		return *m.VideoUrl
	}
	return ""
}

func (m *MaterialMeta) GetVideoPlayUrl() []string {
	if m != nil {
		return m.VideoPlayUrl
	}
	return nil
}

func (m *MaterialMeta) GetVideoPlayValidUrl() []string {
	if m != nil {
		return m.VideoPlayValidUrl
	}
	return nil
}

func (m *MaterialMeta) GetSubTitle() string {
	if m != nil && m.SubTitle != nil {
		return *m.SubTitle
	}
	return ""
}

type MaterialMeta_ImageMeta struct {
	Description      *string  `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Width            *uint32  `protobuf:"varint,2,req,name=width" json:"width,omitempty"`
	Height           *uint32  `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Url              *string  `protobuf:"bytes,4,req,name=url" json:"url,omitempty"`
	Urls             []string `protobuf:"bytes,5,rep,name=urls" json:"urls,omitempty"`
	DateTimestamp    *uint64  `protobuf:"varint,6,opt,name=date_timestamp,json=dateTimestamp" json:"date_timestamp,omitempty"`
	StartTimestamp   *uint64  `protobuf:"varint,7,opt,name=start_timestamp,json=startTimestamp" json:"start_timestamp,omitempty"`
	EndTimestamp     *uint64  `protobuf:"varint,8,opt,name=end_timestamp,json=endTimestamp" json:"end_timestamp,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MaterialMeta_ImageMeta) Reset()                    { *m = MaterialMeta_ImageMeta{} }
func (m *MaterialMeta_ImageMeta) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta_ImageMeta) ProtoMessage()               {}
func (*MaterialMeta_ImageMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

func (m *MaterialMeta_ImageMeta) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *MaterialMeta_ImageMeta) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *MaterialMeta_ImageMeta) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *MaterialMeta_ImageMeta) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *MaterialMeta_ImageMeta) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *MaterialMeta_ImageMeta) GetDateTimestamp() uint64 {
	if m != nil && m.DateTimestamp != nil {
		return *m.DateTimestamp
	}
	return 0
}

func (m *MaterialMeta_ImageMeta) GetStartTimestamp() uint64 {
	if m != nil && m.StartTimestamp != nil {
		return *m.StartTimestamp
	}
	return 0
}

func (m *MaterialMeta_ImageMeta) GetEndTimestamp() uint64 {
	if m != nil && m.EndTimestamp != nil {
		return *m.EndTimestamp
	}
	return 0
}

type MaterialMeta_ExternalMeta struct {
	Url                  *string                                    `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	AdvancedCreativeType *MaterialMeta_ExternalMeta_AdvCreativeType `protobuf:"varint,2,opt,name=advanced_creative_type,json=advancedCreativeType,enum=toutiao_ssp.api.MaterialMeta_ExternalMeta_AdvCreativeType" json:"advanced_creative_type,omitempty"`
	PhoneNumber          *string                                    `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	ButtonText           *MaterialMeta_ExternalMeta_ButtonText      `protobuf:"varint,4,opt,name=button_text,json=buttonText,enum=toutiao_ssp.api.MaterialMeta_ExternalMeta_ButtonText" json:"button_text,omitempty"`
	XXX_unrecognized     []byte                                     `json:"-"`
}

func (m *MaterialMeta_ExternalMeta) Reset()                    { *m = MaterialMeta_ExternalMeta{} }
func (m *MaterialMeta_ExternalMeta) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta_ExternalMeta) ProtoMessage()               {}
func (*MaterialMeta_ExternalMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 1} }

func (m *MaterialMeta_ExternalMeta) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *MaterialMeta_ExternalMeta) GetAdvancedCreativeType() MaterialMeta_ExternalMeta_AdvCreativeType {
	if m != nil && m.AdvancedCreativeType != nil {
		return *m.AdvancedCreativeType
	}
	return MaterialMeta_ExternalMeta_NONE
}

func (m *MaterialMeta_ExternalMeta) GetPhoneNumber() string {
	if m != nil && m.PhoneNumber != nil {
		return *m.PhoneNumber
	}
	return ""
}

func (m *MaterialMeta_ExternalMeta) GetButtonText() MaterialMeta_ExternalMeta_ButtonText {
	if m != nil && m.ButtonText != nil {
		return *m.ButtonText
	}
	return MaterialMeta_ExternalMeta_PHONE_DIAL
}

type MaterialMeta_AndroidApp struct {
	AppName          *string `protobuf:"bytes,1,req,name=app_name,json=appName" json:"app_name,omitempty"`
	DownloadUrl      *string `protobuf:"bytes,2,req,name=download_url,json=downloadUrl" json:"download_url,omitempty"`
	OpenUrl          *string `protobuf:"bytes,3,opt,name=open_url,json=openUrl" json:"open_url,omitempty"`
	Package          *string `protobuf:"bytes,4,opt,name=package" json:"package,omitempty"`
	WebUrl           *string `protobuf:"bytes,5,opt,name=web_url,json=webUrl" json:"web_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MaterialMeta_AndroidApp) Reset()                    { *m = MaterialMeta_AndroidApp{} }
func (m *MaterialMeta_AndroidApp) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta_AndroidApp) ProtoMessage()               {}
func (*MaterialMeta_AndroidApp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 2} }

func (m *MaterialMeta_AndroidApp) GetAppName() string {
	if m != nil && m.AppName != nil {
		return *m.AppName
	}
	return ""
}

func (m *MaterialMeta_AndroidApp) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *MaterialMeta_AndroidApp) GetOpenUrl() string {
	if m != nil && m.OpenUrl != nil {
		return *m.OpenUrl
	}
	return ""
}

func (m *MaterialMeta_AndroidApp) GetPackage() string {
	if m != nil && m.Package != nil {
		return *m.Package
	}
	return ""
}

func (m *MaterialMeta_AndroidApp) GetWebUrl() string {
	if m != nil && m.WebUrl != nil {
		return *m.WebUrl
	}
	return ""
}

type MaterialMeta_IosApp struct {
	AppName          *string `protobuf:"bytes,1,req,name=app_name,json=appName" json:"app_name,omitempty"`
	DownloadUrl      *string `protobuf:"bytes,2,req,name=download_url,json=downloadUrl" json:"download_url,omitempty"`
	OpenUrl          *string `protobuf:"bytes,3,opt,name=open_url,json=openUrl" json:"open_url,omitempty"`
	Appleid          *string `protobuf:"bytes,4,opt,name=appleid" json:"appleid,omitempty"`
	IpaUrl           *string `protobuf:"bytes,5,opt,name=ipa_url,json=ipaUrl" json:"ipa_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MaterialMeta_IosApp) Reset()                    { *m = MaterialMeta_IosApp{} }
func (m *MaterialMeta_IosApp) String() string            { return proto.CompactTextString(m) }
func (*MaterialMeta_IosApp) ProtoMessage()               {}
func (*MaterialMeta_IosApp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 3} }

func (m *MaterialMeta_IosApp) GetAppName() string {
	if m != nil && m.AppName != nil {
		return *m.AppName
	}
	return ""
}

func (m *MaterialMeta_IosApp) GetDownloadUrl() string {
	if m != nil && m.DownloadUrl != nil {
		return *m.DownloadUrl
	}
	return ""
}

func (m *MaterialMeta_IosApp) GetOpenUrl() string {
	if m != nil && m.OpenUrl != nil {
		return *m.OpenUrl
	}
	return ""
}

func (m *MaterialMeta_IosApp) GetAppleid() string {
	if m != nil && m.Appleid != nil {
		return *m.Appleid
	}
	return ""
}

func (m *MaterialMeta_IosApp) GetIpaUrl() string {
	if m != nil && m.IpaUrl != nil {
		return *m.IpaUrl
	}
	return ""
}

type Bid struct {
	Id               *string        `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	AdslotId         *string        `protobuf:"bytes,2,req,name=adslot_id,json=adslotId" json:"adslot_id,omitempty"`
	Price            *uint32        `protobuf:"varint,3,req,name=price" json:"price,omitempty"`
	Adid             *uint64        `protobuf:"varint,4,req,name=adid" json:"adid,omitempty"`
	Creative         *MaterialMeta  `protobuf:"bytes,5,req,name=creative" json:"creative,omitempty"`
	Dealid           *string        `protobuf:"bytes,6,opt,name=dealid" json:"dealid,omitempty"`
	Cid              *string        `protobuf:"bytes,7,opt,name=cid" json:"cid,omitempty"`
	BidAdType        *Bid_BidAdType `protobuf:"varint,8,opt,name=bid_ad_type,json=bidAdType,enum=toutiao_ssp.api.Bid_BidAdType,def=2" json:"bid_ad_type,omitempty"`
	Quality          *float64       `protobuf:"fixed64,9,opt,name=quality" json:"quality,omitempty"`
	Ctr              *float64       `protobuf:"fixed64,10,opt,name=ctr" json:"ctr,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Bid) Reset()                    { *m = Bid{} }
func (m *Bid) String() string            { return proto.CompactTextString(m) }
func (*Bid) ProtoMessage()               {}
func (*Bid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

const Default_Bid_BidAdType Bid_BidAdType = Bid_DSP_AD

func (m *Bid) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Bid) GetAdslotId() string {
	if m != nil && m.AdslotId != nil {
		return *m.AdslotId
	}
	return ""
}

func (m *Bid) GetPrice() uint32 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *Bid) GetAdid() uint64 {
	if m != nil && m.Adid != nil {
		return *m.Adid
	}
	return 0
}

func (m *Bid) GetCreative() *MaterialMeta {
	if m != nil {
		return m.Creative
	}
	return nil
}

func (m *Bid) GetDealid() string {
	if m != nil && m.Dealid != nil {
		return *m.Dealid
	}
	return ""
}

func (m *Bid) GetCid() string {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return ""
}

func (m *Bid) GetBidAdType() Bid_BidAdType {
	if m != nil && m.BidAdType != nil {
		return *m.BidAdType
	}
	return Default_Bid_BidAdType
}

func (m *Bid) GetQuality() float64 {
	if m != nil && m.Quality != nil {
		return *m.Quality
	}
	return 0
}

func (m *Bid) GetCtr() float64 {
	if m != nil && m.Ctr != nil {
		return *m.Ctr
	}
	return 0
}

type SeatBid struct {
	Ads              []*Bid  `protobuf:"bytes,1,rep,name=ads" json:"ads,omitempty"`
	Seat             *string `protobuf:"bytes,2,opt,name=seat" json:"seat,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SeatBid) Reset()                    { *m = SeatBid{} }
func (m *SeatBid) String() string            { return proto.CompactTextString(m) }
func (*SeatBid) ProtoMessage()               {}
func (*SeatBid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SeatBid) GetAds() []*Bid {
	if m != nil {
		return m.Ads
	}
	return nil
}

func (m *SeatBid) GetSeat() string {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return ""
}

type BidResponse struct {
	RequestId        *string    `protobuf:"bytes,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	Seatbids         []*SeatBid `protobuf:"bytes,2,rep,name=seatbids" json:"seatbids,omitempty"`
	ErrorCode        *uint64    `protobuf:"varint,3,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *BidResponse) Reset()                    { *m = BidResponse{} }
func (m *BidResponse) String() string            { return proto.CompactTextString(m) }
func (*BidResponse) ProtoMessage()               {}
func (*BidResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *BidResponse) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *BidResponse) GetSeatbids() []*SeatBid {
	if m != nil {
		return m.Seatbids
	}
	return nil
}

func (m *BidResponse) GetErrorCode() uint64 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

type DspClickNotification struct {
	Dspid            *uint64 `protobuf:"varint,1,opt,name=dspid" json:"dspid,omitempty"`
	ClickUuid        *string `protobuf:"bytes,2,opt,name=click_uuid,json=clickUuid" json:"click_uuid,omitempty"`
	Price            *uint32 `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DspClickNotification) Reset()                    { *m = DspClickNotification{} }
func (m *DspClickNotification) String() string            { return proto.CompactTextString(m) }
func (*DspClickNotification) ProtoMessage()               {}
func (*DspClickNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DspClickNotification) GetDspid() uint64 {
	if m != nil && m.Dspid != nil {
		return *m.Dspid
	}
	return 0
}

func (m *DspClickNotification) GetClickUuid() string {
	if m != nil && m.ClickUuid != nil {
		return *m.ClickUuid
	}
	return ""
}

func (m *DspClickNotification) GetPrice() uint32 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*Pmp)(nil), "toutiao_ssp.api.Pmp")
	proto.RegisterType((*Pmp_Deal)(nil), "toutiao_ssp.api.Pmp.Deal")
	proto.RegisterType((*AdSlot)(nil), "toutiao_ssp.api.AdSlot")
	proto.RegisterType((*AdSlot_Banner)(nil), "toutiao_ssp.api.AdSlot.Banner")
	proto.RegisterType((*Publisher)(nil), "toutiao_ssp.api.Publisher")
	proto.RegisterType((*Content)(nil), "toutiao_ssp.api.Content")
	proto.RegisterType((*Content_Producer)(nil), "toutiao_ssp.api.Content.Producer")
	proto.RegisterType((*App)(nil), "toutiao_ssp.api.App")
	proto.RegisterType((*Geo)(nil), "toutiao_ssp.api.Geo")
	proto.RegisterType((*Device)(nil), "toutiao_ssp.api.Device")
	proto.RegisterType((*Data)(nil), "toutiao_ssp.api.Data")
	proto.RegisterType((*Data_Segment)(nil), "toutiao_ssp.api.Data.Segment")
	proto.RegisterType((*User)(nil), "toutiao_ssp.api.User")
	proto.RegisterType((*PrivateReq)(nil), "toutiao_ssp.api.PrivateReq")
	proto.RegisterType((*PrivateReq_MaterialInfo)(nil), "toutiao_ssp.api.PrivateReq.MaterialInfo")
	proto.RegisterType((*BidRequest)(nil), "toutiao_ssp.api.BidRequest")
	proto.RegisterType((*MaterialMeta)(nil), "toutiao_ssp.api.MaterialMeta")
	proto.RegisterType((*MaterialMeta_ImageMeta)(nil), "toutiao_ssp.api.MaterialMeta.ImageMeta")
	proto.RegisterType((*MaterialMeta_ExternalMeta)(nil), "toutiao_ssp.api.MaterialMeta.ExternalMeta")
	proto.RegisterType((*MaterialMeta_AndroidApp)(nil), "toutiao_ssp.api.MaterialMeta.AndroidApp")
	proto.RegisterType((*MaterialMeta_IosApp)(nil), "toutiao_ssp.api.MaterialMeta.IosApp")
	proto.RegisterType((*Bid)(nil), "toutiao_ssp.api.Bid")
	proto.RegisterType((*SeatBid)(nil), "toutiao_ssp.api.SeatBid")
	proto.RegisterType((*BidResponse)(nil), "toutiao_ssp.api.BidResponse")
	proto.RegisterType((*DspClickNotification)(nil), "toutiao_ssp.api.DspClickNotification")
	proto.RegisterEnum("toutiao_ssp.api.AdType", AdType_name, AdType_value)
	proto.RegisterEnum("toutiao_ssp.api.AdSlot_Position", AdSlot_Position_name, AdSlot_Position_value)
	proto.RegisterEnum("toutiao_ssp.api.Device_ConnectionType", Device_ConnectionType_name, Device_ConnectionType_value)
	proto.RegisterEnum("toutiao_ssp.api.Device_DeviceType", Device_DeviceType_name, Device_DeviceType_value)
	proto.RegisterEnum("toutiao_ssp.api.User_Gender", User_Gender_name, User_Gender_value)
	proto.RegisterEnum("toutiao_ssp.api.BidRequest_BidReqType", BidRequest_BidReqType_name, BidRequest_BidReqType_value)
	proto.RegisterEnum("toutiao_ssp.api.MaterialMeta_ExternalMeta_AdvCreativeType", MaterialMeta_ExternalMeta_AdvCreativeType_name, MaterialMeta_ExternalMeta_AdvCreativeType_value)
	proto.RegisterEnum("toutiao_ssp.api.MaterialMeta_ExternalMeta_ButtonText", MaterialMeta_ExternalMeta_ButtonText_name, MaterialMeta_ExternalMeta_ButtonText_value)
	proto.RegisterEnum("toutiao_ssp.api.Bid_BidAdType", Bid_BidAdType_name, Bid_BidAdType_value)
}

func init() { proto.RegisterFile("3.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2839 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x58, 0x4b, 0x73, 0x1b, 0xc7,
	0xf1, 0x37, 0x16, 0x20, 0x80, 0x6d, 0x3c, 0xb8, 0x1a, 0x51, 0x12, 0x44, 0x3d, 0x4c, 0x43, 0xfe,
	0x5b, 0xfc, 0x3b, 0x29, 0x2a, 0x62, 0xec, 0x3c, 0x54, 0xe5, 0x03, 0x44, 0x80, 0x24, 0x6c, 0x10,
	0x40, 0x0d, 0x41, 0xd9, 0xce, 0x65, 0x6b, 0x80, 0x1d, 0x91, 0x6b, 0x2d, 0x76, 0x57, 0xbb, 0x0b,
	0xc8, 0x3c, 0xa6, 0x52, 0x95, 0x43, 0xce, 0x49, 0x55, 0x72, 0xca, 0x35, 0xf7, 0x7c, 0x8e, 0x5c,
	0x53, 0xc9, 0x21, 0x95, 0x4b, 0x3e, 0x42, 0x2a, 0xe7, 0x54, 0xf7, 0xcc, 0x2e, 0x40, 0x01, 0x92,
	0x9c, 0xaa, 0xe4, 0x80, 0xc2, 0x74, 0x4f, 0x4f, 0x4f, 0x4f, 0x77, 0x4f, 0xcf, 0xaf, 0x17, 0x4a,
	0x3f, 0xdc, 0x0b, 0xa3, 0x20, 0x09, 0xd8, 0x66, 0x12, 0xcc, 0x12, 0x57, 0x04, 0x76, 0x1c, 0x87,
	0x7b, 0x22, 0x74, 0x9b, 0x7f, 0xce, 0x41, 0x7e, 0x38, 0x0d, 0xd9, 0x43, 0xd8, 0x0c, 0x23, 0x77,
	0x2e, 0x12, 0x69, 0x8b, 0xd9, 0x24, 0x71, 0x03, 0xbf, 0x91, 0xdb, 0xc9, 0xed, 0xd6, 0x78, 0x5d,
	0xb3, 0x5b, 0x8a, 0xcb, 0x1e, 0xc1, 0x86, 0x23, 0x85, 0x17, 0x37, 0x8c, 0x9d, 0xfc, 0x6e, 0x65,
	0xff, 0xf6, 0xde, 0x6b, 0x1a, 0xf7, 0x86, 0xd3, 0x70, 0xaf, 0x2d, 0x85, 0xc7, 0x95, 0xdc, 0xf6,
	0x0c, 0x0a, 0x48, 0xb2, 0x3a, 0x18, 0xae, 0xd3, 0xc8, 0xed, 0x18, 0xbb, 0x35, 0x6e, 0xb8, 0x0e,
	0xbb, 0x03, 0xe6, 0xd8, 0x75, 0xec, 0xe7, 0x5e, 0x10, 0x44, 0x0d, 0x83, 0xf6, 0x2a, 0x8f, 0x5d,
	0xe7, 0x10, 0x69, 0xb6, 0x05, 0x1b, 0xaf, 0x62, 0x29, 0x92, 0x46, 0x7e, 0x27, 0xbf, 0x6b, 0x72,
	0x45, 0xb0, 0x6d, 0x28, 0xbf, 0x12, 0x4e, 0x30, 0x15, 0xae, 0xdf, 0x28, 0xd0, 0x44, 0x46, 0xa3,
	0x7a, 0x91, 0x34, 0x36, 0x48, 0x8f, 0x21, 0x92, 0xe6, 0x9f, 0x0a, 0x50, 0x6c, 0x39, 0xa7, 0x5e,
	0x90, 0x2c, 0xed, 0x6c, 0xd2, 0xce, 0x3f, 0x82, 0xe2, 0x58, 0xf8, 0xbe, 0x8c, 0xf4, 0x19, 0xee,
	0xaf, 0x9c, 0x41, 0x2d, 0xdc, 0x7b, 0x4a, 0x52, 0x5c, 0x4b, 0xb3, 0x1f, 0x40, 0x49, 0x38, 0x76,
	0x72, 0x19, 0x4a, 0x32, 0xab, 0xbe, 0x7f, 0x6b, 0xcd, 0xc2, 0xd1, 0x65, 0x28, 0x79, 0x51, 0xd0,
	0xff, 0xd5, 0x33, 0x16, 0x5e, 0x3b, 0xe3, 0x47, 0x90, 0x0f, 0xa7, 0x21, 0x99, 0x5c, 0xd9, 0xdf,
	0x5a, 0xe7, 0x47, 0x8e, 0x02, 0xec, 0xfb, 0xc0, 0x42, 0x91, 0x4c, 0x2e, 0xec, 0xb9, 0xeb, 0xc8,
	0xc0, 0xf6, 0xa4, 0x7f, 0x9e, 0x5c, 0x34, 0x8a, 0xa4, 0xcd, 0xa2, 0x99, 0x67, 0x38, 0xd1, 0x23,
	0x3e, 0xfb, 0x18, 0xae, 0x2d, 0x4b, 0x27, 0x6e, 0xe2, 0xc9, 0x46, 0x69, 0x27, 0xb7, 0x6b, 0xf2,
	0xcd, 0x85, 0xf0, 0x08, 0xd9, 0xec, 0x1e, 0xc0, 0xe4, 0x02, 0xcf, 0xe6, 0xd9, 0xae, 0xd3, 0x28,
	0xef, 0xe4, 0x76, 0x0b, 0xdc, 0xd4, 0x9c, 0xae, 0xc3, 0xee, 0x82, 0x99, 0xb8, 0x53, 0x19, 0x27,
	0x62, 0x1a, 0x36, 0x4c, 0x35, 0x9b, 0x31, 0x30, 0x18, 0x2f, 0xe4, 0xe5, 0xab, 0x20, 0x72, 0xe2,
	0x06, 0xa8, 0x60, 0xa4, 0xf4, 0xf6, 0x2f, 0x73, 0x50, 0x54, 0xce, 0xa3, 0x48, 0xba, 0x4e, 0x72,
	0xa1, 0x23, 0xaf, 0x08, 0x76, 0x13, 0x8a, 0x17, 0xd2, 0x3d, 0xbf, 0x48, 0x1a, 0x06, 0xb1, 0x35,
	0xc5, 0xf6, 0x21, 0x1f, 0x06, 0x71, 0x23, 0xbf, 0x63, 0xec, 0xd6, 0xf7, 0x77, 0xde, 0x14, 0x97,
	0x61, 0x10, 0xbb, 0x98, 0x8c, 0x1c, 0x85, 0xd1, 0x90, 0x58, 0xbe, 0x9c, 0x49, 0x7f, 0x22, 0xc9,
	0xc7, 0x26, 0xcf, 0xe8, 0xe6, 0x31, 0x94, 0x53, 0x61, 0x06, 0x50, 0x3c, 0x1d, 0xf6, 0x5a, 0xa7,
	0xc7, 0x56, 0x8e, 0x95, 0xa1, 0x70, 0xd8, 0xe9, 0xb4, 0x2d, 0x03, 0xb9, 0xed, 0xce, 0xa8, 0xd5,
	0xed, 0x59, 0x05, 0x56, 0x03, 0x93, 0x77, 0x0e, 0x06, 0x27, 0x27, 0x9d, 0x7e, 0xdb, 0x2a, 0xb3,
	0x0a, 0x94, 0x8e, 0x5a, 0xbd, 0x5e, 0x87, 0x7f, 0x6d, 0x59, 0xcd, 0xaf, 0xc1, 0x1c, 0xce, 0xc6,
	0x9e, 0x1b, 0x5f, 0xc8, 0x68, 0x25, 0xa3, 0x18, 0x14, 0x7c, 0x31, 0x95, 0x94, 0xc6, 0x26, 0xa7,
	0x31, 0xb3, 0x20, 0x3f, 0xa1, 0x04, 0x46, 0x16, 0x0e, 0xf1, 0xd0, 0x59, 0xf2, 0x22, 0x53, 0x53,
	0xcd, 0x5f, 0xe5, 0xa1, 0x74, 0x10, 0xf8, 0x89, 0xf4, 0x57, 0x73, 0x75, 0x0b, 0x36, 0x54, 0x08,
	0x95, 0x6a, 0x45, 0xa0, 0xa6, 0x58, 0x46, 0xae, 0x8c, 0xb5, 0x7a, 0x4d, 0xe1, 0x9e, 0xb3, 0xc8,
	0xd3, 0xea, 0x71, 0x78, 0x25, 0x4a, 0x1b, 0xca, 0x39, 0x29, 0xcd, 0x3e, 0x84, 0xda, 0x44, 0x6d,
	0x1b, 0x89, 0xc4, 0xf5, 0xcf, 0x29, 0xa7, 0x4c, 0x7e, 0x95, 0xc9, 0xee, 0x03, 0xcc, 0x62, 0x19,
	0x69, 0x11, 0x95, 0x49, 0x4b, 0x1c, 0xd6, 0x80, 0x12, 0x2d, 0xf8, 0x36, 0xa1, 0x0c, 0x32, 0x79,
	0x4a, 0xb2, 0xcf, 0xa0, 0x1c, 0x46, 0x81, 0x33, 0x9b, 0xc8, 0x88, 0xd2, 0xa7, 0xb2, 0xff, 0xc1,
	0x4a, 0x44, 0xf5, 0xb9, 0xf7, 0x86, 0x5a, 0x90, 0x67, 0x4b, 0xd0, 0x74, 0x4f, 0xf8, 0xe7, 0x33,
	0x71, 0x2e, 0x1b, 0xa0, 0x4c, 0x4f, 0xe9, 0xed, 0xaf, 0xa0, 0x9c, 0xae, 0xf8, 0x2f, 0x07, 0xe3,
	0x8f, 0x06, 0xe4, 0x5b, 0x61, 0xc8, 0xd8, 0x42, 0xeb, 0x13, 0xe3, 0xf1, 0xe3, 0x37, 0x6a, 0x5e,
	0xe8, 0xc9, 0x2f, 0xeb, 0xc1, 0x1d, 0xe7, 0x32, 0x4a, 0x43, 0x31, 0x97, 0x11, 0x4a, 0x8e, 0x67,
	0xbe, 0xe3, 0x49, 0x1d, 0x08, 0x4d, 0x61, 0x18, 0xa8, 0xc6, 0x4e, 0x2e, 0xc3, 0xc0, 0x73, 0x27,
	0x97, 0xfa, 0x6a, 0x5f, 0x65, 0xe2, 0xde, 0xa1, 0x70, 0x1d, 0x0a, 0x40, 0x8d, 0xd3, 0x98, 0xfd,
	0x04, 0xcc, 0x30, 0xcd, 0x49, 0x72, 0x7e, 0x65, 0x7f, 0x7b, 0xb5, 0x8e, 0xa4, 0x12, 0x7c, 0x21,
	0xcc, 0xf6, 0x75, 0xd0, 0xfc, 0x44, 0x47, 0xa6, 0xf1, 0xa6, 0xc8, 0xf0, 0x54, 0xf0, 0xb5, 0x0b,
	0x7f, 0x25, 0x95, 0x9a, 0xbf, 0xc8, 0x41, 0xfe, 0x48, 0x06, 0x78, 0x6a, 0x4f, 0x24, 0xf4, 0x74,
	0xe4, 0x38, 0x0e, 0x89, 0x13, 0xf8, 0xe4, 0x32, 0xe4, 0x04, 0xbe, 0x4a, 0x98, 0x99, 0x9f, 0x44,
	0x97, 0xda, 0x65, 0x29, 0x89, 0x1e, 0x8a, 0xe4, 0x39, 0xbe, 0x3d, 0x3a, 0x26, 0x8a, 0xc2, 0xb3,
	0x4f, 0xdc, 0xe4, 0x52, 0xfb, 0x8d, 0xc6, 0xc8, 0xa3, 0x4a, 0xac, 0x72, 0x96, 0xc6, 0xcd, 0xbf,
	0x15, 0xa0, 0xd8, 0x96, 0x73, 0x77, 0x42, 0x01, 0x77, 0xfc, 0x84, 0xe2, 0x57, 0xe6, 0x38, 0xc4,
	0x34, 0x99, 0x09, 0x2a, 0x37, 0x26, 0x37, 0x66, 0x82, 0xd2, 0x26, 0xd4, 0x16, 0x18, 0x6e, 0x88,
	0xe5, 0xf8, 0x5c, 0x06, 0xb4, 0xf3, 0xba, 0x72, 0x7c, 0x24, 0x03, 0x8e, 0x02, 0x58, 0xd3, 0x1d,
	0xda, 0x03, 0x6b, 0xa6, 0xbe, 0x52, 0x8a, 0xd1, 0x75, 0x58, 0x13, 0x6a, 0xd9, 0xa4, 0x3d, 0x75,
	0x3e, 0xd5, 0xe6, 0x55, 0x52, 0x81, 0x13, 0xe7, 0x53, 0x3a, 0xbf, 0x88, 0x22, 0x57, 0x46, 0xfa,
	0x36, 0xa5, 0xe4, 0x95, 0x8c, 0x2f, 0x5f, 0xcd, 0x78, 0x3c, 0xef, 0x54, 0xbc, 0x90, 0x14, 0x2e,
	0x93, 0xd3, 0x18, 0x8b, 0xc3, 0x34, 0x70, 0xa4, 0xa7, 0xc3, 0xa1, 0x08, 0x3c, 0x58, 0x10, 0x37,
	0x2a, 0xea, 0x60, 0x01, 0x15, 0x85, 0x20, 0x9e, 0x37, 0xaa, 0x2a, 0x13, 0x83, 0x78, 0x8e, 0x12,
	0xdf, 0xc4, 0x8d, 0xda, 0x4e, 0x6e, 0xb7, 0xcc, 0x8d, 0x6f, 0x62, 0x36, 0x80, 0xcd, 0x49, 0xe0,
	0xfb, 0x92, 0x5e, 0x78, 0xf5, 0xc0, 0xd5, 0x77, 0x72, 0xbb, 0xf5, 0xfd, 0x8f, 0x56, 0xdc, 0xa0,
	0xdc, 0x8b, 0xc9, 0xa1, 0xc5, 0xe9, 0xbd, 0xab, 0x4f, 0xae, 0xd0, 0xec, 0x00, 0xf4, 0x89, 0x95,
	0xb2, 0x4d, 0x52, 0xd6, 0x7c, 0x93, 0x32, 0xf5, 0x47, 0x8a, 0xc0, 0xc9, 0xc6, 0xf8, 0x3a, 0x09,
	0xdf, 0x89, 0x02, 0xd7, 0x41, 0x4f, 0x5b, 0x64, 0xbe, 0xa9, 0x39, 0x5d, 0xa7, 0xd9, 0x83, 0xfa,
	0x55, 0x2b, 0xb0, 0x7c, 0x1f, 0x07, 0xbe, 0xbc, 0x9c, 0x04, 0xd3, 0xb1, 0xaa, 0xf1, 0x5f, 0x76,
	0x0f, 0xbb, 0x96, 0x81, 0x85, 0xfc, 0xac, 0xff, 0x45, 0x7f, 0xf0, 0x65, 0xdf, 0xca, 0x33, 0x13,
	0x36, 0xfa, 0x23, 0x7b, 0xff, 0xc8, 0x2a, 0xe8, 0xe1, 0x27, 0x47, 0xd6, 0x46, 0xf3, 0x01, 0xc0,
	0xc2, 0x0c, 0x9c, 0x18, 0x1e, 0x0f, 0xfa, 0x1d, 0x2b, 0x87, 0xef, 0xc3, 0xa8, 0xf5, 0xb4, 0xd7,
	0x19, 0x59, 0x46, 0xf3, 0x0f, 0x39, 0x28, 0xb4, 0x45, 0x22, 0xbe, 0x53, 0xc9, 0xf9, 0x31, 0x94,
	0x62, 0x79, 0x3e, 0xc5, 0x2b, 0x96, 0x27, 0x98, 0x71, 0x6f, 0xf5, 0xfc, 0x22, 0x11, 0x7b, 0xa7,
	0x4a, 0x88, 0xa7, 0xd2, 0xdb, 0x07, 0x50, 0xd2, 0xbc, 0x6c, 0x9f, 0xdc, 0x5b, 0xf6, 0xd9, 0x82,
	0x8d, 0xb9, 0xf0, 0x66, 0x52, 0xa7, 0xb2, 0x22, 0x9a, 0xbf, 0x31, 0xa0, 0x70, 0x16, 0xaf, 0xa9,
	0x8e, 0xb7, 0xa1, 0x3c, 0x9e, 0x5d, 0xca, 0x08, 0x7d, 0xaa, 0xd4, 0x94, 0x88, 0xee, 0x3a, 0x98,
	0x28, 0x97, 0xc1, 0x38, 0x2d, 0x92, 0x97, 0xc1, 0x98, 0x7d, 0x02, 0xc5, 0x73, 0xe9, 0x3b, 0xba,
	0x8e, 0xd5, 0xf7, 0xef, 0xae, 0x1c, 0x01, 0xf7, 0xd8, 0x3b, 0x22, 0x19, 0xae, 0x65, 0xdf, 0xfa,
	0xe6, 0xe8, 0x5b, 0x56, 0x7c, 0xd7, 0x2d, 0xfb, 0x7f, 0x28, 0x38, 0x22, 0x11, 0x8d, 0x12, 0xb9,
	0xee, 0xc6, 0x5a, 0xd7, 0x71, 0x12, 0x69, 0x7e, 0x0f, 0x8a, 0xca, 0x00, 0x8c, 0xf8, 0x49, 0xab,
	0xa7, 0xa3, 0x76, 0xd8, 0xa1, 0xf1, 0xd5, 0xe8, 0x37, 0xff, 0x9a, 0x03, 0x18, 0x2a, 0x44, 0xcb,
	0xe5, 0x4b, 0x76, 0x08, 0xe6, 0x54, 0x24, 0x32, 0x72, 0x11, 0xd1, 0xe6, 0x68, 0xaf, 0xdd, 0xd5,
	0x0a, 0x9a, 0xc9, 0xef, 0x9d, 0x68, 0xe1, 0xae, 0xff, 0x3c, 0xe0, 0x8b, 0xa5, 0x6c, 0x07, 0xaa,
	0x22, 0x92, 0xc2, 0x9e, 0xf8, 0xf6, 0x52, 0x80, 0x00, 0x79, 0x07, 0x7e, 0x1f, 0xc3, 0x74, 0x0b,
	0x4a, 0x24, 0xe1, 0x3a, 0xe9, 0x43, 0x81, 0x64, 0xd7, 0xd9, 0x3e, 0x86, 0xea, 0xb2, 0x56, 0x76,
	0x1d, 0x36, 0x04, 0x65, 0xbc, 0x0a, 0x7b, 0x41, 0x38, 0x5d, 0x87, 0x3d, 0x80, 0x9a, 0x70, 0xe6,
	0x32, 0x4a, 0xdc, 0x78, 0x39, 0x74, 0xd5, 0x05, 0xb3, 0xeb, 0x34, 0xff, 0x91, 0x07, 0x78, 0xea,
	0x3a, 0x1c, 0xc1, 0x4f, 0x9c, 0xe0, 0xfd, 0x89, 0xd4, 0xd0, 0xce, 0x32, 0xc0, 0xd4, 0x9c, 0xae,
	0xc3, 0xde, 0x87, 0x8a, 0x08, 0x5d, 0x7b, 0x2e, 0xa3, 0xd8, 0xa5, 0x02, 0x6d, 0x90, 0xc5, 0xa1,
	0xfb, 0x4c, 0x71, 0xd8, 0x63, 0x84, 0xbb, 0xb1, 0x17, 0x24, 0xb1, 0x4e, 0xe0, 0x5b, 0x6f, 0xc0,
	0x63, 0x3c, 0x95, 0xc3, 0xe8, 0x8a, 0x30, 0x6c, 0x14, 0x76, 0x8c, 0xb5, 0xd1, 0x6d, 0x85, 0x21,
	0x47, 0x01, 0xf6, 0x08, 0x8a, 0xea, 0xa2, 0x37, 0x36, 0x48, 0xf4, 0xd6, 0x1b, 0x4a, 0x03, 0xd7,
	0x62, 0x98, 0x0e, 0x08, 0x39, 0x1a, 0x45, 0x12, 0xbf, 0xb1, 0x36, 0x0d, 0x39, 0x89, 0x30, 0x0e,
	0x55, 0xc4, 0xdc, 0x91, 0x7c, 0xa9, 0x8a, 0x4f, 0xe9, 0x0d, 0x95, 0x6c, 0xe1, 0x29, 0x3d, 0xc4,
	0x9b, 0xff, 0xa4, 0x3c, 0xe8, 0xf7, 0xbe, 0xb6, 0xdb, 0xa7, 0x43, 0x0e, 0xe3, 0x8c, 0xcb, 0x1e,
	0x41, 0x21, 0x8c, 0xe4, 0x4b, 0xfd, 0xc6, 0xde, 0x79, 0x4b, 0x86, 0x70, 0x12, 0x64, 0x37, 0xa0,
	0xe8, 0xc4, 0x21, 0xfa, 0xdd, 0x54, 0xb0, 0xd7, 0x89, 0xc3, 0xae, 0xd3, 0x3c, 0x48, 0x03, 0x44,
	0x5a, 0xaf, 0x41, 0x8d, 0x76, 0xe3, 0x9d, 0x51, 0x8b, 0x1f, 0x75, 0x46, 0x56, 0x8e, 0x55, 0x21,
	0x33, 0xc0, 0x32, 0xd8, 0x16, 0x58, 0xe9, 0x9c, 0xdd, 0xea, 0xb7, 0x89, 0x9b, 0x6f, 0xfe, 0x6e,
	0x73, 0x91, 0x31, 0x27, 0x32, 0x11, 0xcb, 0x7d, 0x49, 0x8e, 0x80, 0xf3, 0x3b, 0xfb, 0x12, 0xac,
	0x23, 0x08, 0x14, 0x55, 0xd0, 0x69, 0xbc, 0x40, 0x9a, 0xf9, 0xd7, 0x91, 0x66, 0x30, 0x8b, 0x08,
	0x5a, 0x1b, 0x84, 0x34, 0x89, 0x62, 0x9f, 0x43, 0xd5, 0x9d, 0x8a, 0x73, 0x69, 0xeb, 0x4e, 0x4a,
	0x75, 0x31, 0x0f, 0x57, 0x36, 0x5e, 0x36, 0x74, 0xaf, 0x8b, 0x2b, 0x70, 0xc4, 0x2b, 0xb4, 0x58,
	0xb7, 0x08, 0x87, 0x50, 0x96, 0xdf, 0x26, 0x32, 0xf2, 0x85, 0xa7, 0x0b, 0xc3, 0xc7, 0x6f, 0xd7,
	0xd3, 0xd1, 0xd2, 0xa4, 0x2a, 0x5b, 0xcb, 0xba, 0x50, 0x49, 0x1f, 0x0c, 0xcc, 0xc2, 0x12, 0xa9,
	0xda, 0x7d, 0xbb, 0xaa, 0x96, 0x5a, 0x80, 0x99, 0x99, 0xbe, 0x36, 0x88, 0xfe, 0x3e, 0x83, 0x92,
	0x1b, 0xc4, 0xa4, 0x46, 0xc5, 0xfc, 0xc3, 0x77, 0x9c, 0x2c, 0x88, 0x51, 0x45, 0xd1, 0xa5, 0x7f,
	0x2c, 0xb2, 0xf1, 0x45, 0xf0, 0xca, 0x46, 0x1f, 0x9b, 0xd4, 0x1b, 0x95, 0x90, 0x3e, 0x8b, 0x3c,
	0x84, 0x0f, 0x13, 0xcf, 0x9d, 0xbc, 0xa0, 0x39, 0xdd, 0x37, 0x11, 0x03, 0x27, 0x6f, 0x43, 0xd9,
	0x8d, 0x6d, 0xd7, 0xc7, 0x7d, 0x2b, 0xf4, 0x3c, 0x97, 0xdc, 0xb8, 0x8b, 0x24, 0x16, 0x67, 0x84,
	0xd8, 0xfa, 0x15, 0x47, 0x78, 0x7d, 0x1f, 0x2a, 0x5e, 0x68, 0x07, 0xa1, 0xf4, 0x49, 0x57, 0x4d,
	0x3d, 0x90, 0x5e, 0x38, 0x08, 0xa5, 0x8f, 0xca, 0x1e, 0xc1, 0x96, 0xea, 0x01, 0x43, 0x4f, 0x5c,
	0xda, 0x71, 0x22, 0xa2, 0x84, 0x04, 0xeb, 0xb4, 0xe9, 0x35, 0x9a, 0x1b, 0x7a, 0xe2, 0xf2, 0x14,
	0x67, 0x70, 0xc1, 0x63, 0xb8, 0xb1, 0xb4, 0xe0, 0xb9, 0xeb, 0xbb, 0xf1, 0x05, 0xad, 0xd8, 0xa4,
	0x15, 0x2c, 0x5b, 0x71, 0x48, 0x53, 0xb8, 0xe4, 0x01, 0xd4, 0x54, 0x42, 0xd8, 0x62, 0x2e, 0x12,
	0x11, 0xe9, 0x67, 0xba, 0xaa, 0x98, 0x2d, 0xe2, 0x31, 0x0e, 0x56, 0x1c, 0x7a, 0x22, 0xbe, 0xb0,
	0x27, 0x91, 0x14, 0x89, 0x3b, 0x97, 0x71, 0xe3, 0x1a, 0x55, 0x94, 0xef, 0x9c, 0x2f, 0x9b, 0x4a,
	0xc1, 0x41, 0xba, 0x1e, 0xdd, 0xa8, 0x6c, 0x45, 0xfb, 0x98, 0x7a, 0x64, 0x88, 0x81, 0x56, 0x7d,
	0x08, 0xf5, 0xa5, 0x83, 0xa0, 0xc4, 0x75, 0x3a, 0x41, 0x35, 0x3b, 0xc1, 0xaa, 0x7f, 0xe6, 0xc2,
	0x73, 0x1d, 0x92, 0xdd, 0x7a, 0xcd, 0x3f, 0xcf, 0x70, 0x46, 0x87, 0x2e, 0x9e, 0x8d, 0x75, 0x4b,
	0x7d, 0x43, 0x77, 0x9a, 0xb3, 0x31, 0xf5, 0xd2, 0xdb, 0xff, 0xca, 0x81, 0x99, 0xd9, 0xcb, 0x76,
	0x10, 0x00, 0xc5, 0x93, 0xc8, 0x0d, 0xb3, 0x4f, 0x29, 0x84, 0x02, 0x33, 0xd6, 0xa2, 0x2f, 0x36,
	0xd6, 0xf7, 0xc5, 0x79, 0xc2, 0xf9, 0x69, 0x5f, 0x9c, 0x35, 0x76, 0x46, 0xda, 0xd8, 0x31, 0x28,
	0xcc, 0x22, 0x0f, 0x1f, 0x58, 0xb4, 0x96, 0xc6, 0xec, 0xff, 0xa0, 0xee, 0x88, 0x44, 0xda, 0x8b,
	0xae, 0xbd, 0x48, 0x5d, 0x7b, 0x0d, 0xb9, 0xa3, 0xac, 0x73, 0x7f, 0x08, 0x9b, 0x2a, 0x1b, 0x16,
	0x72, 0x25, 0x92, 0xab, 0x13, 0x7b, 0x21, 0xf8, 0x00, 0x6a, 0xd2, 0x77, 0x96, 0xc4, 0xd4, 0x27,
	0x82, 0xaa, 0xf4, 0x9d, 0x4c, 0x68, 0xfb, 0x2f, 0x79, 0xa8, 0x2e, 0x5f, 0xc8, 0xd4, 0xd6, 0xdc,
	0xc2, 0xd6, 0x10, 0x6e, 0x0a, 0x67, 0x2e, 0xfc, 0x89, 0x74, 0xb2, 0x14, 0x50, 0xf5, 0xca, 0xa0,
	0xe2, 0xfc, 0xe4, 0xbb, 0x5f, 0xf7, 0xbd, 0x96, 0x33, 0x4f, 0xb3, 0x80, 0x4a, 0xda, 0x56, 0xaa,
	0x79, 0x99, 0xcb, 0x3e, 0x80, 0x6a, 0x78, 0x11, 0xf8, 0xd2, 0xf6, 0x67, 0xd3, 0xb1, 0x8c, 0x74,
	0x4d, 0xab, 0x10, 0xaf, 0x4f, 0x2c, 0xf6, 0x0c, 0x2a, 0xe3, 0x59, 0x92, 0x20, 0xe0, 0xc5, 0x8b,
	0xa5, 0x00, 0xce, 0xa7, 0xff, 0x81, 0x25, 0x4f, 0x69, 0xf5, 0x48, 0x7e, 0x9b, 0x70, 0x18, 0x67,
	0xe3, 0xe6, 0x43, 0xd8, 0x7c, 0xcd, 0x46, 0xc4, 0x25, 0x7d, 0x44, 0x93, 0xef, 0x21, 0x2e, 0x69,
	0x1d, 0x8c, 0xba, 0x83, 0xbe, 0x65, 0x34, 0x7f, 0x9f, 0x03, 0x58, 0xe8, 0x60, 0x75, 0x00, 0xc2,
	0x9c, 0x76, 0xbb, 0xdb, 0xea, 0x59, 0xef, 0xb1, 0xeb, 0xb0, 0x79, 0x30, 0xe8, 0x9f, 0x9e, 0xf5,
	0x46, 0xf6, 0xf1, 0x60, 0xd4, 0xeb, 0x12, 0x1a, 0xbd, 0x06, 0x35, 0x25, 0xa4, 0xa7, 0x2c, 0x83,
	0x6d, 0x42, 0xa5, 0x35, 0x1a, 0xf4, 0x0f, 0xf4, 0xc2, 0x3c, 0xca, 0xa4, 0x0b, 0x15, 0x88, 0x2d,
	0x30, 0x0b, 0xaa, 0x87, 0xbc, 0xd3, 0xc9, 0x14, 0x6d, 0x20, 0xe7, 0xf3, 0x41, 0xb7, 0x9f, 0x71,
	0x8a, 0xf4, 0x1a, 0xf1, 0x76, 0x87, 0x67, 0xac, 0xd2, 0xf6, 0x6f, 0x73, 0x00, 0x8b, 0x02, 0x89,
	0xd5, 0x49, 0x84, 0xa1, 0x02, 0x38, 0x2a, 0xba, 0x25, 0x11, 0x86, 0x84, 0x6e, 0x3e, 0x80, 0xaa,
	0x13, 0xbc, 0xf2, 0xbd, 0x40, 0xa8, 0x3b, 0xa4, 0x1e, 0x96, 0x4a, 0xca, 0xd3, 0xb5, 0x2d, 0xab,
	0x55, 0xba, 0xef, 0x0b, 0x74, 0xa5, 0x6a, 0x40, 0x29, 0x14, 0x93, 0x17, 0xd8, 0xf6, 0xa8, 0xc6,
	0x2f, 0x25, 0x11, 0x35, 0xbd, 0x92, 0x63, 0x5a, 0xa3, 0x9b, 0xe6, 0x57, 0x72, 0x7c, 0x16, 0x79,
	0xdb, 0xbf, 0xce, 0x41, 0xb1, 0x9b, 0x15, 0xdb, 0xff, 0x99, 0x59, 0x22, 0x0c, 0x3d, 0xe9, 0x3a,
	0xa9, 0x59, 0x9a, 0x44, 0xb3, 0xdc, 0x50, 0x2c, 0x9b, 0xe5, 0x86, 0xe2, 0x2c, 0xf2, 0x9a, 0xff,
	0x34, 0x20, 0xff, 0xd4, 0x75, 0x56, 0x50, 0xf7, 0x1d, 0x30, 0x15, 0x46, 0x52, 0xd8, 0x0d, 0xd9,
	0x65, 0xc5, 0xe8, 0xd2, 0x37, 0x9e, 0x30, 0x42, 0x30, 0x94, 0x57, 0xa5, 0x80, 0x08, 0xbc, 0xe0,
	0xc2, 0xa1, 0xad, 0x8d, 0xdd, 0x02, 0xa7, 0x31, 0xfb, 0x29, 0x94, 0xd3, 0xfb, 0xa3, 0x91, 0xd3,
	0xbd, 0xb7, 0x26, 0x2c, 0xcf, 0xc4, 0xe9, 0x3b, 0x85, 0xc4, 0x4a, 0xa6, 0x5b, 0x52, 0x4d, 0xd1,
	0x97, 0x11, 0xfd, 0x59, 0xc1, 0xe4, 0x38, 0x64, 0x87, 0x50, 0x41, 0x00, 0x95, 0x42, 0x8a, 0x32,
	0x5d, 0x8c, 0xfb, 0xeb, 0xf0, 0x13, 0xfe, 0x14, 0xb2, 0x78, 0x52, 0x6c, 0x9f, 0x0e, 0xed, 0x56,
	0x9b, 0x9b, 0xe3, 0x94, 0x85, 0xee, 0x7b, 0x39, 0x13, 0x1e, 0x36, 0xee, 0x26, 0x75, 0xff, 0x29,
	0x49, 0x7b, 0x26, 0x11, 0x75, 0xad, 0x39, 0x8e, 0xc3, 0xe6, 0x67, 0x60, 0x66, 0xba, 0x30, 0xa3,
	0x17, 0xb0, 0xa7, 0xad, 0xd0, 0xbc, 0x52, 0x6f, 0x19, 0x78, 0x2d, 0xfa, 0x83, 0xbe, 0xbd, 0x2c,
	0x90, 0x6f, 0x76, 0xb0, 0x65, 0x12, 0x09, 0x7a, 0x1e, 0x21, 0xa8, 0x93, 0x62, 0xf9, 0xad, 0xb5,
	0xa8, 0x0f, 0x05, 0xd0, 0xbd, 0xf4, 0x81, 0x59, 0xb7, 0x52, 0x38, 0x6e, 0xfe, 0x3c, 0x07, 0x15,
	0xc2, 0x67, 0x71, 0x18, 0xf8, 0xb1, 0x7c, 0x17, 0x82, 0xfe, 0x04, 0xca, 0xb8, 0x6c, 0xec, 0x3a,
	0xe9, 0xd7, 0xf0, 0xd5, 0xaf, 0x28, 0xda, 0x2c, 0x9e, 0x49, 0xa2, 0x52, 0x19, 0x45, 0x41, 0x64,
	0x4f, 0x02, 0x47, 0x81, 0xad, 0x02, 0x37, 0x89, 0x73, 0x10, 0x38, 0xb2, 0x29, 0x60, 0xab, 0x1d,
	0x87, 0x07, 0x88, 0x08, 0xfa, 0x41, 0xe2, 0x3e, 0x77, 0x27, 0x22, 0x7d, 0x2f, 0x9c, 0x38, 0xd4,
	0x6d, 0x41, 0x81, 0x2b, 0x82, 0xbe, 0xe0, 0x2a, 0x34, 0x31, 0xcb, 0x9a, 0x02, 0x85, 0x2f, 0xce,
	0x66, 0xee, 0x95, 0xcc, 0xca, 0x65, 0x99, 0xf5, 0xf1, 0xdf, 0xe9, 0xd3, 0x38, 0xb9, 0xfa, 0x36,
	0xdc, 0x18, 0x0d, 0xce, 0x46, 0xdd, 0xd6, 0xc0, 0x3e, 0xec, 0x74, 0xda, 0x76, 0x6f, 0x68, 0xf7,
	0xd0, 0xaf, 0x56, 0x6e, 0xdd, 0xd4, 0xe9, 0x49, 0xab, 0xd7, 0xb3, 0x0c, 0xb6, 0x0d, 0x37, 0xaf,
	0x4c, 0xb5, 0x86, 0xe9, 0xb2, 0xc2, 0xda, 0x39, 0xb5, 0x2e, 0xcf, 0xee, 0xc1, 0xed, 0x74, 0x4e,
	0x7d, 0x73, 0x45, 0xa5, 0x47, 0xbc, 0x35, 0x3c, 0xee, 0x1e, 0x58, 0x1b, 0xec, 0x2e, 0x34, 0x56,
	0xa7, 0x9f, 0xb6, 0xfa, 0xfd, 0x0e, 0xb7, 0x8a, 0x18, 0xf8, 0xd1, 0x59, 0xab, 0xff, 0xb3, 0x6e,
	0xa6, 0xd7, 0x2a, 0xad, 0xd1, 0x88, 0xfb, 0xe9, 0x35, 0x26, 0xdb, 0x81, 0xbb, 0xab, 0x1a, 0x47,
	0x9d, 0xaf, 0x46, 0x76, 0xf7, 0xa4, 0x75, 0xd4, 0xb1, 0x60, 0xdd, 0x29, 0x8f, 0xf8, 0xe0, 0x6c,
	0x68, 0x55, 0xd8, 0x2d, 0xb8, 0x9e, 0x4e, 0x3d, 0xeb, 0xb6, 0x3b, 0x03, 0x7b, 0xd8, 0x1a, 0x1d,
	0x1c, 0x5b, 0x55, 0xc6, 0xa0, 0xde, 0xef, 0x8c, 0xbe, 0x1c, 0xf0, 0x2f, 0x6c, 0xfd, 0x41, 0xb9,
	0x86, 0xbc, 0x54, 0x58, 0xf3, 0xea, 0xac, 0x01, 0x5b, 0xed, 0x25, 0x8b, 0x33, 0xdf, 0x6e, 0xae,
	0x99, 0x51, 0x2e, 0xb2, 0xd6, 0xcc, 0x28, 0x73, 0xae, 0xad, 0x75, 0xac, 0x9a, 0x63, 0xec, 0x3e,
	0x6c, 0xa7, 0x73, 0xd9, 0x07, 0xec, 0x85, 0xd6, 0xeb, 0xeb, 0x4e, 0x49, 0x47, 0xb2, 0xb6, 0xd6,
	0xaa, 0x55, 0x73, 0x37, 0xd8, 0xfb, 0x70, 0x67, 0x55, 0xed, 0x22, 0xa0, 0x37, 0xd9, 0x4d, 0x60,
	0xa9, 0x80, 0xfe, 0x52, 0x6e, 0xf7, 0x86, 0xd6, 0xad, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb5,
	0xd9, 0x69, 0x8d, 0x70, 0x1a, 0x00, 0x00,
}
